---
title: "Graficas Usuario VS Tiempo de carga para reporte de Hot Sale"
author: "**Israel Valencia**"
date: "Mayo 2020"
df_print: paged
geometry: margin=1.2cm
classoption: landscape
output: 
   pdf_document
---

```{r echo=FALSE, results='hide',collapse=TRUE, message=FALSE,warning=FALSE}
library(readxl)
library(reshape2)
library(ggplot2)
library(tidyverse)
library(here)
library(lubridate)


tabla <- read_excel("/home/israel_valencia/Escritorio/1/HotSale/DatosHotsale.xlsx",3) #Lee la hoja 3 del excel

fecha=strptime('22/May/2020:00:00:00',format='%d/%b/%Y:%H:%M:%S')
fecha
Inicio=(day(fecha)-22)*24+2
Inicio

fecha_final=Sys.Date()-days(1); #la feha del dia anterior a la fecha actual, cuando ya se actualice el archivo, lo corres y se va a agregar todo desde el 22 de MAyo hasta lo del dia anterior a la fecha actual

fecha_final
Fin=(day(fecha_final)-22)*24+25
Fin

DATE<-c(fecha)

for(i in 1:(Fin-1)){
  DATE[i]<- fecha+hours(i-1)
}

#Coppel.com Tienda
UsuariosCCT<-tabla[Inicio:Fin,3]
TiempoCCT<-tabla[Inicio:Fin,4]

COPPELCOMTIENDA<-data.frame(DATE, UsuariosCCT,TiempoCCT)
names(COPPELCOMTIENDA) <- c("FECHA", "UsuariosCCT","TiempoCCT")

COPPELCOMTIENDA$UsuariosCCT <- as.numeric(COPPELCOMTIENDA$UsuariosCCT)
COPPELCOMTIENDA$TiempoCCT <- as.numeric(COPPELCOMTIENDA$TiempoCCT)


#Coppel.com
UsuariosCC<-tabla[Inicio:Fin,8]
TiempoCC<-tabla[Inicio:Fin,9]

COPPELCOM<-data.frame(DATE, UsuariosCC,TiempoCC)
names(COPPELCOM) <- c("FECHA", "UsuariosCC","TiempoCC")

COPPELCOM$UsuariosCC <- as.numeric(COPPELCOM$UsuariosCC)
COPPELCOM$TiempoCC <- as.numeric(COPPELCOM$TiempoCC)


```

```{r echo=FALSE, results='asis',collapse=TRUE, message=FALSE,warning=FALSE, fig.height = 9, fig.width = 43, fig.align = "center"}

 #Coppel.com Tienda
a=range(COPPELCOMTIENDA$UsuariosCCT)
b=range(COPPELCOMTIENDA$TiempoCCT)
m=diff(a)/diff(b)

y2<-((COPPELCOMTIENDA$TiempoCCT-b[1])*m+a[1])

p <- ggplot(COPPELCOMTIENDA, aes(x = FECHA)) 
p<-p+ geom_line(aes(y =UsuariosCCT ,color="Usuarios"),size=3)
p <- p + scale_y_continuous(name ="Usuarios", 
                             breaks=seq(0,max(COPPELCOMTIENDA$UsuariosCCT),as.integer(max(COPPELCOMTIENDA$UsuariosCCT)/10)), labels = seq(0,max(COPPELCOMTIENDA$UsuariosCCT),as.integer(max(COPPELCOMTIENDA$UsuariosCCT)/10)),sec.axis = sec_axis(~(./m -a[1]/m)+b[1], name = "Segundos",                             breaks=seq(0,as.integer(max(COPPELCOMTIENDA$TiempoCCT))+1,(as.integer(max(COPPELCOMTIENDA$TiempoCCT) +1)/10)), 
labels = seq(0,as.integer(max(COPPELCOMTIENDA$TiempoCCT))+1,(as.integer(max(COPPELCOMTIENDA$TiempoCCT)+1)/10))),
                             ) + 
theme_minimal()+theme(axis.text = element_text(size = rel(2.5)),axis.title.y.right = element_text(margin = margin(t = 0, r =20, b = 0, l = 20)))+ggtitle("Coppel.com Tienda")+ theme(  plot.title = element_text(color="blue", size=rel(4), face="italic"),
     axis.title.x = element_text(color="#000000", size=rel(3)),
     axis.title.y = element_text(color="#000000", size=rel(3)))+xlab(" ")

 p<-p+ geom_line(aes(y =y2,color="Segundos"),size=3)+scale_color_manual(name=" ",                     values=c("Segundos"="orange","Usuarios"="#0096f2"),                                                labels=c("Segundos","Usuarios"))+theme(legend.position="bottom", legend.text = element_text( size = rel(3)),legend.key.width = unit(3,"cm"))

print(p)
```
```{r echo=FALSE, results='asis',collapse=TRUE, message=FALSE,warning=FALSE, fig.height = 9, fig.width = 43, fig.align = "center"}

 #Coppel.com
          
a=range(COPPELCOM$UsuariosCC)
b=range(COPPELCOM$TiempoCC)
m=diff(a)/diff(b)

y2<-((COPPELCOM$TiempoCC-b[1])*m+a[1])


q <- ggplot(COPPELCOM, aes(x = FECHA)) 
q<-q+ geom_line(aes(y =UsuariosCC, colour="Usuarios"),size=3)
q <- q + scale_y_continuous(name ="Usuarios", 
 breaks=seq(0,max(COPPELCOM$UsuariosCC),as.integer(max(COPPELCOM$UsuariosCC)/10)),                    labels=seq(0,max(COPPELCOM$UsuariosCC),as.integer(max(COPPELCOM$UsuariosCC)/10)),
 sec.axis = sec_axis(~(./m -a[1]/m)+b[1], name = "Segundos",                           breaks=seq(0,as.integer(max(COPPELCOM$TiempoCC))+1,(as.integer(max(COPPELCOM$TiempoCC) +1)/10)), labels = seq(0,as.integer(max(COPPELCOM$TiempoCC))+1,(as.integer(max(COPPELCOM$TiempoCC)+1)/10))), 
                           limits = c(0,max(COPPELCOM$UsuariosCC))) + 
  theme_minimal()+theme(axis.text = element_text(size = rel(2.5)),axis.title.y.right = element_text(margin = margin(t = 0, r =20, b = 0, l = 20)))+ggtitle("Coppel.com")+ theme(plot.title = element_text(color="blue", size=rel(4), face="italic"),
                        axis.title.x = element_text(color="#000000", size=rel(3)),
                        axis.title.y =element_text(color="#000000",size=rel(3))) +xlab(" ")
q<-q+ geom_line(aes(y =y2,color="Segundos"),size=3)+scale_color_manual(name=" ",
                                                                          values=c("Usuarios"="#0096f2","Segundos"="orange"),                                               labels=c("Segundos","Usuarios"))+
theme(legend.position="bottom",legend.text = element_text(size = rel(3)),legend.key.width = unit(3,"cm"))
print(q)

```